### PR TITLE
MoreCTM addon by me

### PR DESCRIPTION
**Pull request by Pomik108**
please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please add this soon kthxbai

### CODE REVIEW

**Comment by xMrVizzy** [comment]
you should change folder name to lower_case! I mean: morectm or more_ctm

**Comment by Pomik108** [comment]
ok, will do

**Comment by xMrVizzy** [comment]
No no no you should update folder name to lowercase not a Name in info.yaml

**Comment by Pomik108** [comment]
oh

**Comment by Pomik108** [comment]
@xMrVizzy done

**Pull request merged**
