### PR TITLE
Create stacked_items

### PR DESCRIPTION
**Pull request by RobertRR11**

### CODE REVIEW

**Comment by xMrVizzy** [comment]
You should create folder named stacked_items, and include image.png(or other format) and info.yml, info.yml example here - https://github.com/FaithfulTeam/Addons/tree/master/faithful_3d

**Comment by xMrVizzy** [comment]
if you don't have any url, example website or screenshots just remove key and value I mean (Remove website: http://example.)

**Comment by RobertRR11** [comment]
I can't create a folder only a file

**Comment by xMrVizzy** [comment]
Click create new file and type in file name - stacked_items/

**Comment by RobertRR11** [comment]
And what do I need to do after that?

**Comment by xMrVizzy** [comment]
than add a 2 file in folder and pull request

**Pull request closed without merging**
